### ISSUE TITLE
logs in, doesn't post

### ISSUE THREAD

**Issue by zzzrevenue** [Takenobou/instaReposter#2]
hey I appreciate you released this, however I've been trying out your script but it's not actually posting the photos into my instagram account, I can't see what I'm doing wrong here, i've been trying to figure out for two days now

**Comment by Takenobou** [comment]
I'm really sorry, it is not a user error. At first i thought it was an EXIF data problem (fixed in v0.4.1), which worked for a while, but it seems that it no longer works. I will try to get a fix up soon. 

~In the meantime use v0.3.1, that was the last working without a hitch.~ - See reply below

**Comment by Takenobou** [comment]
https://github.com/LevPasha/Instagram-API-python/issues/705

Turns out my script is ok, there is a temporary bug with the API that i use that will be fixed soon. Sorry about this.

**Comment by zzzrevenue** [comment]
Thanks for the reply, yeah I just couldn’t figure it out what I was doing wrong on my part, let’s hope the api functions properly soon.

**Comment by Takenobou** [comment]
It seems to be fixed, I am able to upload consistently.
