### ISSUE TITLE
Instagram API Outdated?

### ISSUE THREAD

**Issue by DEAD1SIDE** [Takenobou/instaReposter#3]
Hey. I just wanted to use you program but it didnt posted the image so i tried to troubleshoot and i found out that the Github for the [Instagram API](https://github.com/LevPasha/Instagram-API-python) is not longer there. The[ pip Packet](https://pypi.org/project/InstagramAPI/) is still online.
Could it be that there was a update to Instagram so it doesnt work anymore?
I'm not that good with python but maybe[ this API](https://github.com/ping/instagram_private_api) could be a replacement.

**Comment by Takenobou** [comment]
Sorry yeh, it’s been outdated for a while now, Instagram has a new API and I don’t have the  interest in this project to update it. I think there are some new restrictions with the new API but if you are running this on a computer with a gui, you could get selenium to spoof a browser. The only script that doesn’t work is autoPost.py, the others should work. Just use the correct parameters and you should be up and running. If I get the time to quickly update, I’ll update this thread.

**Comment by DEAD1SIDE** [comment]
Thanks man and no problem. Maybe I will find some time to look into it and learn a bit more Python. My basic knowledge isnt enough for this. Stay save and healthy.

**Comment by Takenobou** [comment]
Sorry dude, I think this code is dead. Instagram has closed the endpoint for uploading images to the public, its only available to businesses now :/, that api has the same issue as the last one. I cant get passed the image bulk selection using selenium and I haven't found any solutions for it. So i guess thats it :/ The image grabbing still works so if you want to collect images and post manually, you can still do that, just remove lines 45-53 on instaReposter.py and bring down lines 55-64 one indentation, it should then start populating the folder indefinitely and you can grab the ones you want. Its not really a solution but its the best I can do atm :/
